[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "pango",
  "libx11",
  "libxcb",
  "gtk3"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"